apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdemo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate  # Specify the update strategy as Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: k8sdemo-container
          image: subodhdere/k8sdemo:v3

---
apiVersion: v1
kind: Service
metadata:
  name: k8sdemo-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

